### ISSUE TITLE
Rooms: Door Frames 

### ISSUE THREAD

**Issue by cajoho99** [TeknikIT/SpiritsJourney#5]
<h1>Empty Door Frames</h1>
<h2>Space for Doors</h2>
All rooms need to be fitted with an empty space for doors. The doors will be inserted at a later time but the rooms still need an opening for them to go.
<h2>Door Models</h2>
We need some kind of door model that will fit the rooms

**Comment by Mailer-Arch** [comment]
Door model has been created.
Door spaces have been created.
To be connected in-game.

**Door Model:** https://github.com/TeknikIT/SpiritsJourney/commit/a9fd4dcfa52783bdc9fb0fd2d1e3333328d63220
